services:
  apache-php:
    build:
      context: _docker/apache-php
      dockerfile: Dockerfile
      args:
        INSTALL_COMPOSER: "true"        # change requires container rebuild
        INSTALL_WKHTMLTOPDF: "false"    # change requires container rebuild
    container_name: apache-php-${COMPOSE_PROJECT_NAME}
    environment:
      PHP_INI_SCAN_DIR: ":/usr/local/etc/php/conf.d/additional-inis"
    volumes:
      - ./:/var/www/html
      - ./_docker/apache-php/additional-inis:/usr/local/etc/php/conf.d/additional-inis
      - ./_docker/apache-php/sites-available:/etc/apache2/sites-available
    ports:
      - ${APACHE_PORT}:80

  mariadb:
    image: jbergstroem/mariadb-alpine:10.4.15  # alpine image is a lot smaller than official mariadb image
    container_name: mariadb-${COMPOSE_PROJECT_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./_docker/mariadb:/docker-entrypoint-initdb.d
      - ./_docker/mariadb/my.cnf:/etc/my.cnf.d/my.cnf
    ports:
      - ${MARIADB_PORT}:3306