services:
  web:
    build:
      context: _docker/web
      dockerfile: Dockerfile
      args:
        INSTALL_WKHTMLTOPDF: "false"    # change requires container rebuild
    container_name: web-${COMPOSE_PROJECT_NAME}
    command: sh -c "./_docker/web/scripts/startup.sh"
    environment:
      PHP_INI_SCAN_DIR: ":/usr/local/etc/php/conf.d/additional-inis"
      COMPOSER_INSTALL_PATH: ./
#      NPM_INSTALL_PATH: ./
    env_file: .env
    volumes:
      - ./:/var/www/html
      - ./_docker/web/additional-inis:/usr/local/etc/php/conf.d/additional-inis
      - ./_docker/web/sites-available:/etc/apache2/sites-available
      - ${HOSTS_FILE}:/tmp/hostsfile
    ports:
      - "${LOOPBACK_IP}:80:80"
    depends_on:
      - mariadb

  mariadb:
    image: jbergstroem/mariadb-alpine:10.4.15  # alpine image is a lot smaller than official mariadb image
    container_name: mariadb-${COMPOSE_PROJECT_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./_docker/mariadb:/docker-entrypoint-initdb.d
      - ./_docker/mariadb/my.cnf:/etc/my.cnf.d/my.cnf
    ports:
      - "${MARIADB_PORT}:3306"