services:
  web:
    build:
      context: _docker/web
      dockerfile: Dockerfile
      args:
        INSTALL_WKHTMLTOPDF: "false"    # change requires container rebuild
    container_name: web-${COMPOSE_PROJECT_NAME}
    command: /var/www/html/_docker/web/scripts/startup.sh
    environment:
      PHP_INI_SCAN_DIR: ":/usr/local/etc/php/conf.d/additional-inis"
      TEMPLATE_CONFIG: "database_config.php:./application/config/database_config.php"
      WKHTMLTOPDF_BINARY: "/usr/bin/wkhtmltopdf"
      COMPOSER_INSTALL_PATHS: ./
      #NPM_INSTALL_PATHS: ./
    env_file:
      - .env
      - public.env
    volumes:
      - ./:/var/www/html
      - ./_docker/web/additional-inis:/usr/local/etc/php/conf.d/additional-inis
      - ./_docker/web/sites-available:/etc/apache2/sites-available
      - ./_docker/web/certs:/etc/apache2/ssl
      - ${HOSTS_FILE}:/tmp/hostsfile
    ports:
      - "${LOOPBACK_IP:-127.255.255.254}:80:80"
      - "${LOOPBACK_IP:-127.255.255.254}:443:443"
      - "${EXTERNAL_IP:-127.255.255.253}:80:80"
    depends_on:
      - db

  db:
    build: _docker/db
    container_name: db-${COMPOSE_PROJECT_NAME}
    hostname: ${DOMAIN}
    environment:
      MYSQL_ROOT_PASSWORD: root
    env_file:
      - .env
      - public.env
    volumes:
      - ./_docker/db:/docker-entrypoint-initdb.d
      - ./_docker/db/my.cnf:/etc/my.cnf.d/my.cnf
    ports:
      - "${LOOPBACK_IP:-127.255.255.254}:3307:3306"