services:
  web:
    build:
      context: _docker/web
      dockerfile: Dockerfile
      args:
        # changes to one of the following requires container rebuild
        INSTALL_COMPOSER: "true"
        INSTALL_NPM: "false"
        INSTALL_GRUNT: "false"
        INSTALL_WKHTMLTOPDF: "false"
        INSTALL_LOCALES: "de_DE"
    image: ${PROJECT_NAME}-web
    container_name: ${PROJECT_NAME}-web
    command: /var/www/html/_docker/web/scripts/startup.sh
    environment:
      PHP_INI_SCAN_DIR: ":/usr/local/etc/php/conf.d/additional-inis"
      #TEMPLATE_CONFIG: "database_config.php:./application/config/database_config.php"
      WKHTMLTOPDF_BINARY: "/usr/bin/wkhtmltopdf"
      COMPOSER_INSTALL_PATHS: ./
      #NPM_INSTALL_PATHS: ./
      #CONTAINS_GIT_SUBMODULES: "false"
    env_file:
      - .env
      - _docker/public.env
    cap_add:
      - NET_ADMIN  # needed to make changes to iptables
    volumes:
      - ./:/var/www/html
      - ./_docker/web/additional-inis:/usr/local/etc/php/conf.d/additional-inis
      - ./_docker/web/sites-available:/etc/apache2/sites-available
      - ./_docker/web/certs:/etc/apache2/ssl
      - ${HOSTS_FILE}:/tmp/hostsfile
    ports:
      - "${LOOPBACK_IP:-127.255.255.254}:${WEB_PORT:-80}:80"
      - "${LOOPBACK_IP:-127.255.255.254}:${WEB_PORT_SSL:-443}:443"
      - "${LOOPBACK_IP:-127.255.255.254}:${CATCH_MAIL_PORT:-8025}:8025"
      - "${EXTERNAL_IP:-127.255.255.253}:${WEB_PORT:-80}:80"
    depends_on:
      - db

  db:
    build: _docker/db
    image: ${PROJECT_NAME}-db
    container_name: ${PROJECT_NAME}-db
    hostname: ${DOMAIN}
    environment:
      MYSQL_ROOT_PASSWORD: root
    env_file:
      - .env
      - _docker/public.env
    volumes:
      - ./_docker/db/scripts:/docker-entrypoint-initdb.d
      - ./_docker/db/sql:/sql-files
      - ./_docker/db/my.cnf:/etc/my.cnf.d/my.cnf
    ports:
      - "${LOOPBACK_IP:-127.255.255.254}:${DB_PORT:-3306}:3306"