services:
  web:
    build:
      context: _docker/web
      dockerfile: Dockerfile
      args:
        INSTALL_WKHTMLTOPDF: "false"    # change requires container rebuild
    container_name: web-${COMPOSE_PROJECT_NAME}
    command: sh -c "/var/www/html/_docker/web/startup.sh ${COMPOSE_PROJECT_NAME} ${LOOPBACK_IP} ${DOMAIN}"
    environment:
      PHP_INI_SCAN_DIR: ":/usr/local/etc/php/conf.d/additional-inis"
    volumes:
      - ./:/var/www/html
      - ./_docker/web/additional-inis:/usr/local/etc/php/conf.d/additional-inis
      - ./_docker/web/sites-available:/etc/apache2/sites-available
      - ${HOSTS_FILE}:/tmp/hostsfile
    ports:
      - "${LOOPBACK_IP}:80:80"
    depends_on:
      - mariadb

  mariadb:
    image: jbergstroem/mariadb-alpine:10.4.15  # alpine image is a lot smaller than official mariadb image
    container_name: mariadb-${COMPOSE_PROJECT_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./_docker/mariadb:/docker-entrypoint-initdb.d
      - ./_docker/mariadb/my.cnf:/etc/my.cnf.d/my.cnf
    ports:
      - "${MARIADB_PORT}:3306"

  composer-install:
    container_name: composer-install-${COMPOSE_PROJECT_NAME}
    image: composer:2
    volumes:
      - ./:/app
    command: composer install --ignore-platform-reqs

#  npm-install:
#    image: node:15.7-alpine3.12
#    container_name: npm-install-${COMPOSE_PROJECT_NAME}
#    working_dir: /app
#    command: npm install --no-update-notifier
#    volumes:
#      - ./:/app