services:
  apache-php:
    build:
      context: _docker/apache-php
      dockerfile: Dockerfile
      args:
        INSTALL_WKHTMLTOPDF: ${INSTALL_WKHTMLTOPDF}
    container_name: apache-php-${COMPOSE_PROJECT_NAME}
    environment:
      PHP_INI_SCAN_DIR: ":/usr/local/etc/php/conf.d/additional-inis"
    volumes:
      - ./:/var/www/html
      - ./_docker/apache-php/additional-inis:/usr/local/etc/php/conf.d/additional-inis
      - ./_docker/apache-php/sites-available:/etc/apache2/sites-available
    ports:
      - ${APACHE_PORT}:80

  mariadb:
    image: mariadb:10.5
    container_name: mariadb-${COMPOSE_PROJECT_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./_docker/mariadb:/docker-entrypoint-initdb.d
    ports:
      - ${MARIADB_PORT}:3306

  composer-install:
    image: composer:latest
    container_name: composer-install-${COMPOSE_PROJECT_NAME}
    command: ["composer", "install"]
    working_dir: /app
    volumes:
      - ./:/app